sudo: required
dist: trusty
language: python
python: "2.7"

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo sed -i "s/\DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry=172.30.0.0\/16 /g" /etc/default/docker
  - sudo cat /etc/default/docker
  - sudo service docker restart

install: 
  - pip install ansible
  - pip install openshift
  - pip install jmespath

before_script:
  - bash ci/prepare.sh

script:
  - ansible-playbook all.yml

notifications:
 email:
   on_success: never
on_failure: never
