- hosts: localhost
  vars:
    with_backup: true
    with_restore: true
  vars_prompt:
    - name: user
      prompt: "Cluster login"
      private: no
  roles:
  - login_ocp
  - deployment/nginx_deployment
