---
apiVersion: v1
kind: Namespace
metadata:
  name: service-example
  labels:
    name: my-service

# Basic test
---
kind: Service
apiVersion: v1
metadata:
  name: my-service-basic
  namespace: service-example
  labels:
    name: my-service
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9376
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9377                       

# External name type
---
kind: Service
apiVersion: v1
metadata:
  name: my-service-external-name
  namespace: service-example
  labels:
    name: my-service
spec:
  type: ExternalName
  externalName: my.database.example.com

# Node port type
---
kind: Service
apiVersion: v1
metadata:
  name: my-service-node-port
  namespace: service-example
  labels:
    name: my-service
spec:
  type: NodePort
  ports:
   - port: 8081
     nodePort: 31514

# Load Balancer without selector
---
kind: Service
apiVersion: v1
metadata:
  name: my-service-load-balancer
  namespace: service-example
  labels:
    name: my-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  loadBalancerIP: 78.11.24.19
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155

# Load balancer with selector
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-service
  namespace: service-example
  labels:
    name: my-service
spec:
  template:
    metadata:
      labels:
        app: nginx
        name: my-service
    spec:
      containers:
      - image: docker.io/twalter/openshift-nginx
        name: nginx
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    name: my-service
  name: nginx-load-balanser
  namespace: service-example
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: nginx
  type: LoadBalancer
