---
apiVersion: ark.heptio.com/v1
kind: Restore
metadata:
  name: hellopod-backup
  namespace: heptio-ark
spec:
  backupName: hellopod-backup
  excludedResources:
  - node
  - events
  - events.events.k8s.io
  - backups.ark.heptio.com
  - restores.ark.heptio.com
  includedNamespaces:
  - '*'
