---
apiVersion: ark.heptio.com/v1
kind: Backup
metadata:
  name: net-pol-backup
  namespace: heptio-ark
spec:
  labelSelector:
    matchLabels:
      test: net-policy
  storageLocation: default
  ttl: 720h0m0s
  includedNamespaces:
  - '*'
