- name: Create service account
  block:
    - name: Create service account, role and role binding
      k8s:
        state: present
        definition: "{{ lookup('file', 'basic-sa-role-template.yml')}}"

- name: Create backup
  when: with_backup
  block:
    - name: Create backup
      include_role:
        name: backup
      vars:
        backup_name: sa-role-backup
        backup_label: basic-sa-role

- name: Restore service account
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore
      vars:
        restore_name: sa-role-restore
        backup_name: sa-role-backup
        namespace_to_delete: basic-sa-role

    - name: Wait 2 minutes for service account to appear
      k8s_facts:
        api_version: v1
        kind: ServiceAccount
        namespace: basic-sa-role
        name: basic-sa
      register: service_account
      until: service_account and (service_account.resources | length > 0)
      retries: 10
      delay: 10

    - name: Wait 2 minutes for role to appear
      k8s_facts:
        api_version: rbac.authorization.k8s.io/v1beta1
        kind: Role
        namespace: basic-sa-role
        name: basic-role
      register: role
      until: role and (role.resources | length > 0)
      retries: 10
      delay: 10

    - name: Wait 2 minutes for role binding to appear
      k8s_facts:
        api_version: rbac.authorization.k8s.io/v1beta1
        kind: RoleBinding
        namespace: basic-sa-role
        name: basic-role-binding
      register: role_binding
      until: role_binding and (role_binding.resources | length > 0)
      retries: 10
      delay: 10
