- name: Create resources
  block:
    - name: Create etcd-sts-operator
      k8s:
        state: present
        definition: "{{ lookup('file', 'etcd-sts-operator-template.yml')}}"
      register: deploy
      retries: 10
      delay: 3
      until: deploy is succeeded

    - name: Check resource presence
      include: check.yml
  when: with_resources

- name: Create backup
  include_role:
    name: backup
  when: with_backup

- name: Restore service
  when: with_restore
  block:
    - name: Start restoring 
      include_role:
        name: restore

    - name: Check resource presence
      include: check.yml
